# yum abd apt module
# conditions
# privilege

- name: installation file 
  hosts: all
  become: true
  gather_facts: yes

  tasks: 
    - name: install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: install httpd
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_os_family == "RedHat"   


    - name: install httpd
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"   

    - name: install nginx
      package:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: start nginx
      service:
        name: nginx
        state: started
        enbled: yes
        

    - name: print list
      debug:
        msg: "{{ item }}"
      loop:
        - apple
        - banana
        - mango          